name: Build and Push

on:
  push:
    branches:
      - main

env:
  COMMIT_TYPE: ${{ contains(fromJSON('["!:", "BREAKING CHANGE:"]'), github.event.head_commit.message) && 'major' || startsWith('feat', github.event.head_commit.message) && 'minor' || startsWith('fix', github.event.head_commit.message) && 'patch' }}

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          fetch-depth: 0
      - name: Validate HEAD Commit
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npx commitlint --from HEAD~1 --to HEAD --verbose

  build:
    needs: commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Version
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          export VERSION=$(git tag --sort=-creatordate | grep -v main | head -n 1)
          export VERSION_BITS=$(echo $VERSION | sed "s/v//g" | sed "s/\./ /g")
          # TODO: This prints the wrong values
          export PUBLISH_TAG_VERSION_MAJOR=${VERSION_BITS[1]}
          export PUBLISH_TAG_VERSION_MINOR=${VERSION_BITS[2]}
          export PUBLISH_TAG_VERSION_PATCH=${VERSION_BITS[3]}

      - name: Build
        run: make build

      - name: Push
        run: make push
