name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Version
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          export VERSION=$(git tag --sort=-creatordate | grep -v main | head -n 1)
          export VERSION_BITS=$(echo $VERSION | sed "s/v//g" | sed "s/\./ /g")
          # TODO: This prints the wrong values
          export PUBLISH_TAG_VERSION_MAJOR=${VERSION_BITS[1]}
          export PUBLISH_TAG_VERSION_MINOR=${VERSION_BITS[2]}
          export PUBLISH_TAG_VERSION_PATCH=${VERSION_BITS[3]}

      - name: Build
        run: make build

      - name: Push
        run: make push
